### ISSUE TITLE
Make all options work

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#29]
- Options that have been implemented in the generic dtbook-to-pef should not be overwritten.
- Options that were not generic enough to implement in the generic dtbook-to-pef should be implemented here.

Ammar has already fixed `$page-width`, `$page-height` and `$hyphenation` in https://github.com/snaekobbi/pipeline-mod-nlb/commit/dab14906ae791e0e6d457cb017ab7c42df43113f. Jostein has implemented `$show-print-page-numbers` in https://github.com/snaekobbi/pipeline-mod-nlb/commit/582e43538dd48b5c3c6f5b82416051ada1da0360. But there are some other options left (thinking about `$show-braille-page-numbers` for example). Ideally all options, especially the ones implemented here, should be covered by unit tests.

**Comment by josteinaj** [comment]
I agree, we should go through and check all the options for this.

It can be impractical to write tests for the entire script to test script options though. When writing tests for the entire script, where the input is a DTBook and the output is a PEF, it's useful to filter out only the portion of the PEF that is relevant for the test so that small changes to the default CSS don't require updating the expected output for all tests. Currently I filter the output for a couple of tests here:
- https://github.com/snaekobbi/pipeline-mod-nlb/blob/master/src/test/xprocspec/test_dtbook-to-pef.xprocspec#L177
- https://github.com/snaekobbi/pipeline-mod-nlb/blob/master/src/test/xprocspec/test_dtbook-to-pef.xprocspec#L266

This works fairly well, but what would be even more useful is if there were a way to get the portion of the PEF that corresponds to a given input element. So for instance, if I have a `<h1 id="h1">...</h1>`, it would be really useful if I could get the corresponding rows in the PEF like this:

``` xml
<x:context label="result">
    <x:document type="file" base-uri="temp-dir" href="6/pef-output-dir/book.pef" select="//pef:row[@input-id='h1']"/>
</x:context>
```

...or similar. Such annotated PEFs would have to be enabled with some "debug" option.

I'm not familiar with the OBFL stuff etc. so I don't know how difficult that would be to implement. Maybe it's easier to just put some marker in the input text that can be easily retrieved by comparing the text nodes of the output (essentially what I do in the filtering now).

**Comment by bertfrees** [comment]
Yeah I saw that, I thought that was pretty smart.

Annotated PEFs. That's something I've thought about too. But it's probably a bit too ambitious. It doesn't sound impossible, but whether we'll have time for it is another thing. So I don't know, I haven't got great hopes for it.

**Comment by josteinaj** [comment]
Ok, I'll use the current approach with matching the text nodes then. I think it's good enough.

**Comment by josteinaj** [comment]
This issue was moved to nlbdev/pipeline#7
