### ISSUE TITLE
Non-standard hyphenation patterns

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#38]
The framework now has support for non-standard hyphenation, but in order to use it we are missing the patterns for Norwegian. @usama49 @josteinaj Who can try to find out if there are existing tables with these patterns in them already? If yes we can incorporate them. If not we should be able to generate them if we have source data.

**Comment by josteinaj** [comment]
Cool. We haven't built a big list of patterns because we were not sure of the input format yet. We wanted to try it out with just a couple of works first to see that it works. But we have some material that we'll try to generate a patterns list from.

So I assume we need to plug something into [NLBTranslator.java](https://github.com/snaekobbi/pipeline-mod-nlb/blob/master/src/main/java/no/nlb/pipeline/braille/impl/NLBTranslator.java)? I'll have to look closer at [DefaultLineBreakerTest.java](https://github.com/daisy/pipeline-mod-braille/blob/a74951afc281ba0ae8e2b4d30ea2112ee8752827/pipeline-braille-utils/common-utils/src/test/java/org/daisy/pipeline/braille/common/DefaultLineBreakerTest.java) to see how non-standard hyphenation works.

**update**: we discussed this in todays call. We'll have another look at the hyphenation branch to try and build our own hyphenation tables.

**Comment by bertfrees** [comment]
I'll prepare something in mod-nlb with a couple of patterns so you can see how it works. We don't have to use libhyphen patterns for non-standard hyphenation, for example if a rule-based approach is more suitable we could implement a custom hyphenator in Java, but using libhyphen will make it easier to combine standard with non-standard hyphenation I think.

**Comment by bertfrees** [comment]
@usama49 and @josteinaj: see commit https://github.com/snaekobbi/pipeline-mod-nlb/commit/1f019ee5bfff421a394f0038f8aa73f327c41b54. I had to make some additional changes in the translator to make non-standard hyphenation work. Then I've added a file with one non-standard pattern and a few tests. I had to disable test_dtbook-to-pef because some stuff on the title pages is hyphenated wrongly. This is because on the "hyphenation" branch the hyphenation table from OpenOffice is replaced by a completely custom one.

**Comment by josteinaj** [comment]
Cool! I got it building (just had to change from osx to linux deps). We're experimenting now :)

**Comment by bertfrees** [comment]
This is finished, branch just needs to be merged.

**Comment by josteinaj** [comment]
Yes, I'll merge it soon, @usama49 has some stuff to finish first and then I'll merge everything to master.
