### ISSUE TITLE
sheets/pages

### ISSUE THREAD

**Issue by KariRudjord** [snaekobbi/pipeline-mod-nlb#52]
Change from sheets to pages i GUI. Maximum pages should be 86 (Jostein).
Keep sheets in CSS Sheets should be 43 (Ammar). 
Total amount of pages must be pages, not sheets. (Ammar/Bert)

We will communicate this to braille producers. It will only be a challenge when printing on every second page, and that we don't do often.

@josteinaj @usama49 @bertfrees

**Comment by bertfrees** [comment]
- [x] Total amount of pages must be pages, not sheets: see https://github.com/snaekobbi/pipeline-mod-nlb/issues/32#issuecomment-225145600
- [ ] Change from sheets to pages in GUI: This requires a change in the script (new option) and in the CSS (new option must be divided by 2 to obtain the value for max-length. The only difficulty is that in order to be able to add a new option to the script, you'll have to use the lower-level steps `px:dtbook-to-pef.convert` and `px:dtbook-to-pef.store`. There is an example of how to do this in mod-sbs: https://github.com/snaekobbi/pipeline-mod-sbs/blob/master/src/main/resources/xml/dtbook-to-pef.xpl.

**Comment by josteinaj** [comment]
This issue was moved to nlbdev/pipeline#15
