### ISSUE TITLE
Automatic volume breaking

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#58]
Wish/claim from NLB:

- All volumes are about the same size
- The first text page in a volume is always full (volume does not begin with the end of a chapter)
- Do not split a &lt;p&gt; in two volumes, move it to the new volume.

**Comment by bertfrees** [comment]
A part of it is already supported, and just needs to be tested. Another part (notably not splitting a &lt;p&gt; in two volumes) is not supported yet.

See https://github.com/daisy/pipeline-mod-braille/issues/136.

**Comment by josteinaj** [comment]
A suggestion for a volume breaking algorithm:
1. If at page 70, there is a headline, break just before that headline
2. If at page 70, there is no headline in the two preceding or two following pages, then break after the last full paragraph on that page
3. Otherwise do steps 1-2 for page 69
4. Otherwise do steps 1-2 for page 68
5. ...
6. Otherwise do steps 1-2 for page 4
7. Otherwise break after last full paragraph on page 70
8. Otherwise break after last full text node on page 70
9. Otherwise break after page 70

**Comment by josteinaj** [comment]
This issue was moved to nlbdev/pipeline#20
